# Hardware configuration for native NixOS
#
# This file is tracked in git and should be generated once on the target system.
#
# Initial setup:
#   1. Boot from NixOS installer USB and partition disks
#   2. Mount filesystems to /mnt
#   3. Generate hardware config: nixos-generate-config --root /mnt
#   4. Clone this dotfiles repo to /mnt/home/ro/dotfiles
#   5. Copy hardware config:
#      cp /mnt/etc/nixos/hardware-configuration.nix \
#         /mnt/home/ro/dotfiles/nix/systems/native/hardware-configuration.nix
#   6. Install: nixos-install --flake /mnt/home/ro/dotfiles#nixos-native
#
# For hardware changes (rare):
#   sudo nixos-generate-config --show-hardware-config > \
#     /home/ro/dotfiles/nix/systems/native/hardware-configuration.nix
#   git commit and rebuild

{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  # PLACEHOLDER: Replace with actual hardware configuration
  # Generated by: nixos-generate-config --root /mnt
  #
  # Example structure (will vary by hardware):

  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  # Replace UUIDs with actual values from your system
  fileSystems."/" = {
    device = "/dev/disk/by-uuid/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/XXXX-XXXX";
    fsType = "vfat";
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
