name: 'Setup Nix'
description: 'Install Nix and optionally configure Cachix'
inputs:
  cachix-auth-token:
    description: 'Cachix authentication token (optional)'
    required: false
runs:
  using: 'composite'
  steps:
    - name: Install Nix
      uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ github.token }}

    - name: Setup Cachix (numtide)
      if: ${{ inputs.cachix-auth-token != '' }}
      uses: cachix/cachix-action@v16
      with:
        name: numtide
        authToken: ''
