name: Nix Neovim

on:
  push:
    paths:
      - 'nvim/**'
      - 'flake.nix'
      - '.github/workflows/nix-neovim.yaml'
  workflow_call:
  workflow_dispatch:

jobs:
  neovim-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-nix

      - name: Check Neovim configuration
        run: nix run .#nvim-restore
        env:
          DOTFILES_DIR: ${{ github.workspace }}
